install.packages("sp")
install.packages("raster")
install.packages("rgdal")
install.packages("ggplot2")
install.packages("agricolae")
install.packages("reshape2")
install.packages("devtools")
install.packages("ggrepel")
install.packages("lme4")
install.packages("plyr")
install.packages("DescTools")
install.packages("doParallel")
install.packages('parallel')
install.packages('foreach')
install.packages('maptools')
install.packages("BiocManager")
BiocManager::install("EBImage")
devtools::install_github("filipematias23/FIELDimageR", dependencies=FALSE)
